services:
  nginx:
    build:
      context: nginx-proxy
      dockerfile: dockerfile
    image: app-nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - web
      - api

  web:
    build:
      context: web
      dockerfile: dockerfile.prod
    image: app-web-prod

  api:
    build:
      context: api
      dockerfile: dockerfile.prod
    image: app-api-prod
