services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: web/dockerfile.dev
    image: app-web-dev
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app/web
          ignore:
            - node_modules
        - action: sync
          path: ./packages/eslint-config
          target: /app/packages/eslint-config
        - action: rebuild
          path: ./web/package.json
        - action: rebuild
          path: ./web/pnpm-lock.yaml
        - action: rebuild
          path: ./tsconfig.base.json
        - action: rebuild
          path: ./packages/eslint-config/package.json

  api:
    build:
      context: .
      dockerfile: api/dockerfile.dev
    image: app-api-dev
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "4000"
      NODE_ENV: "development"
      APP_REDIS: "redis://redis:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    command:
      [
        "sh",
        "-c",
        "TS_NODE_PROJECT=tsconfig.json pnpm exec ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js schema:sync -f src/ormconfig.ts && pnpm run dev",
      ]
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app/api
          ignore:
            - node_modules
        - action: rebuild
          path: ./pnpm-lock.yaml
        - action: rebuild
          path: ./tsconfig.base.json
