import type { ProjectRow } from '../model'

import { BASE_CURRENCY } from '@/shared'

const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`

export const projectsMock: ProjectRow[] = [
  {
    key: '1',
    name: 'Project 1',
    paid: `${BASE_CURRENCY.symbol}80.5`,
    status: 'Active',
    timeTotal: 4 * 60 + 10,
    timeActive: 2 * 60 + 10,
    keyboard: '4 983',
    mouse: '1 827',
    mouseDistance: '2 385 910',
    publishedIn: 'Personal',
    startDate: new Date(),
    rate: `${BASE_CURRENCY.symbol}20/hour`,
    description: lorem,
  },
  {
    key: '2',
    name: 'Project 2',
    paid: `${BASE_CURRENCY.symbol}63.1`,
    status: 'Active',
    timeTotal: 2 * 60 + 56,
    timeActive: 1 * 60 + 24,
    keyboard: '3 854',
    mouse: '947',
    mouseDistance: '1 839 352',
    publishedIn: 'Personal',
    startDate: new Date(),
    rate: `${BASE_CURRENCY.symbol}20/hour`,
    description: lorem,
  },
  {
    key: '3',
    name: 'Project 3',
    paid: `${BASE_CURRENCY.symbol}839.5`,
    status: 'Active',
    timeTotal: 12 * 60 + 36,
    timeActive: 10 * 60 + 59,
    keyboard: '24 093',
    mouse: '3 811',
    mouseDistance: '9 386 154',
    publishedIn: 'Personal',
    startDate: new Date(),
    rate: `${BASE_CURRENCY.symbol}20/hour`,
    description: lorem,
  },
  {
    key: '4',
    name: 'Project 4',
    paid: `${BASE_CURRENCY.symbol}65`,
    status: 'Paused',
    timeTotal: 4 * 60 + 12,
    timeActive: 1 * 60 + 44,
    keyboard: '3 852',
    mouse: '724',
    mouseDistance: '1 245 431',
    publishedIn: 'Personal',
    startDate: new Date(),
    rate: `${BASE_CURRENCY.symbol}20/hour`,
    description: lorem,
  },
]
